apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: nginx
  annotations:
    deployment.kubernetes.io/change-cause: "Initial deployment of web-rollingup-strategy"
    deployment.kubernetes.io/revision: "1"
    deployment.kubernetes.io/strategy: "RollingUpdate"\
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service 
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  #type: ClusterIP
  #type: NodePort
  #type: ExternalName
          
